import { typeCreator } from '../shared';

export const {
  CLEAR_HOODS_ON_POINT,
  DESELECT_HOOD,
  SELECT_HOOD,
  SET_HOOD_NAME,
  SET_HOODS_ON_POINT,
  TOGGLE_HOOD_SELECTED,
  SET_HOODS,
  ADD_HOODS,
  HOVER_HOOD,
  USER_ADD_HOODS,
  EDIT_HOOD,
  SAVE_HOOD,
  AFTER_SAVE_HOOD,
  DRAW_HOOD,
} = typeCreator;
