version: "3"
services:
  nginx:
    build: ./nginx
    links:
      - app
    ports:
      - "80:80"
    restart: always
  db:
    build: ./sql
    environment:
      - POSTGRES_PASSWORD=${PGPASSWORD}
    restart: always
    volumes:
      - ./data:/var/lib/postgresql/data
  app:
    build: .
    ports:
      - "8080:8080"
    links:
      - db
    environment:
      - PGPASSWORD
    restart: always
