version: "3"
services:
  nginx:
    image: gcr.io/${PROJECT_ID}/nginx:latest
    links:
      - app
    ports:
      - "80:80"
      - "443:443"
    restart: always
  db:
    image: gcr.io/${PROJECT_ID}/db:latest
    environment:
      - POSTGRES_PASSWORD=${PGPASSWORD}
    restart: always
    volumes:
      - data:/var/lib/postgresql/data
  app:
    image: gcr.io/${PROJECT_ID}/app:latest
    ports:
      - "8080:8080"
    links:
      - db
    environment:
      - PGPASSWORD
      - GOOGLE_API_KEY
      - SENDGRID_API_KEY
    restart: always
volumes:
  data:
