steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'youhood-fe:$REVISION_ID', '-f', 'infra/web/Dockerfile', '.']
- name: 'youhood-fe:$REVISION_ID'
  args: []
  dir: '/srv'
  volumes:
  - name: 'vol'
    path: '/srv'
  secretEnv: ['GOOGLE_API_KEY']
- name: 'gcr.io/cloud-builders/gsutil'
  args: ['cp', '-a', 'public-read', '/srv/public/*', 'gs://youhood.io/']
  volumes:
  - name: 'vol'
    path: '/srv'
- name: 'gcr.io/cloud-builders/gsutil'
  args: ['cp', '-a', 'public-read', '/srv/public/images/*', 'gs://youhood.io/images']
  volumes:
  - name: 'vol'
    path: '/srv'
secrets:
- kmsKeyName: projects/youhood-192019/locations/global/keyRings/storage/cryptoKeys/youkey
  secretEnv:
    GOOGLE_API_KEY: CiQADz5/6ateBuHCiJsz2TfujkMklKAw4hqtC8iMl1tM11H69sASUQAHlPNfBdOSVaxH3gCGROSW0dCbua7y4DraCHh2MjytkaeIe8XLf+q5lx2KaiPZfmBlAD2CV2lXIP1kOOHuLvcdJhFoLWbyqewFZ7i6v5SO4g==
